version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: node-red-standalone_web_1
      APP_PORT: 1881
      # Used to allow (HTTP In) flows to be publicly exposed
      PROXY_AUTH_WHITELIST: "/public/*"
  
  web:
    image: nodered/node-red:3.0.2@sha256:e2cd6b89e18361593276e3ef5282b403e0879040c96d3099c15e8f0200a36339
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      PORT: 1881
